/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* floating-point amr_nb audio codec */
/* #undef AMR_NB */

/* fixed-point amr_nb audio codec */
/* #undef AMR_NB_FIXED */

/* floating-point amr_wb audio codec */
/* #undef AMR_WB */

/* building for Alpha platform */
/* #undef ARCH_ALPHA */

/* building for ARM platform */
/* #undef ARCH_ARMV4L */

/* building for MIPS platform */
/* #undef ARCH_MIPS */

/* building for PowerPC platform */
/* #undef ARCH_POWERPC */

/* building for Sh4 platform */
/* #undef ARCH_SH4 */

/* building for Sparc64 platform */
/* #undef ARCH_SPARC64 */

/* building for x86 platform */
#define ARCH_X86 1

/* runtime liba52.so.0 resolving */
/* #undef CONFIG_A52BIN */

/* GPL A52 support via liba52 */
/* #undef CONFIG_AC3 */

/* BeOS audio support */
/* #undef CONFIG_AUDIO_BEOS */

/* OSS audio support */
/* #undef CONFIG_AUDIO_OSS */

/* Building for Darwin */
/* #undef CONFIG_DARWIN */

/* compilation of decoders */
#define CONFIG_DECODERS 1

/* DV IEEE1394 support */
/* #undef CONFIG_DV1394 */

/* compilation of encoders */
#define CONFIG_ENCODERS 1

/* faac support via libfaac */
/* #undef CONFIG_FAAC */

/* faad support via libfaad */
/* #undef CONFIG_FAAD */

/* runtime libfaad.so.0 resolving */
/* #undef CONFIG_FAADBIN */

/* ffmpeg command line utility */
/* #undef CONFIG_FFMPEG */

/* ffmpeg media player */
#define CONFIG_FFPLAY 1

/* ffmpeg media server */
/* #undef CONFIG_FFSERVER */

/* whether dlfcn.h is available */
#define CONFIG_HAVE_DLFCN 1

/* whether dlopen is available */
#define CONFIG_HAVE_DLOPEN 1

/* mp3 encoding via libmp3lame */
/* #undef CONFIG_MP3LAME */

/* high-precision (slower) MPEG audio */
/* #undef CONFIG_MPEGAUDIO_HP */

/* rtp/http networking code */
#define CONFIG_NETWORK 1

/* Building for OS/2 */
/* #undef CONFIG_OS2 */

/* post-processing functions */
/* #undef CONFIG_PP */

/* patent-encumbered codecs */
#define CONFIG_RISKY 1

/* Building for SunOS */
/* #undef CONFIG_SUNOS */

/* video4linux support */
/* #undef CONFIG_VIDEO4LINUX */

/* vorbis support via libvorbis */
/* #undef CONFIG_VORBIS */

/* Building for Win32 (cygwin/mingw32) */
/* #undef CONFIG_WIN32 */

/* use zlib for decompression */
#define CONFIG_ZLIB 1

/* Emulate fast integer types */
/* #undef EMULATE_FAST_INT */

/* Emulate inttypes.h if not available */
/* #undef EMULATE_INTTYPES */

/* use Altivec optimizations */
/* #undef HAVE_ALTIVEC */

/* altivec.h available */
/* #undef HAVE_ALTIVEC_H */

/* Have built-in vector types */
#define HAVE_BUILTIN_VECTOR 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* profiling with gprof */
/* #undef HAVE_GPROF */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* whether localtime_r() is available */
#define HAVE_LOCALTIME_R 1

/* whether lrintf() is available */
#define HAVE_LRINTF 1

/* whether malloc.h available */
#define HAVE_MALLOC_H 1

/* whether memalign() is available */
#define HAVE_MEMALIGN 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* support for Sun Media Lib */
/* #undef HAVE_MLIB */

/* use MMI optimizations */
/* #undef HAVE_MMI */

/* use MMX optimizations */
#define HAVE_MMX 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* video hooking plugins */
/* #undef HAVE_VHOOK */

/* Name of package */
#define PACKAGE "ffmpeg"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "FFMpeg"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "FFMpeg 0.4.8"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "ffmpeg"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.4.8"

/* enable powerpc performance reporting */
/* #undef POWERPC_PERFORMANCE_REPORT */

/* runtime libpostproc.so linking */
/* #undef SHARED_PP */

/* simple IDCT routines */
#define SIMPLE_IDCT 1

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.4.8"

/* processor is big-endian */
/* #undef WORDS_BIGENDIAN */

/* Number of bits in a file offset, on hosts where this is settable. */
#define _FILE_OFFSET_BITS 64

/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif

/* Define for large files, on AIX-style hosts. */
/* #undef _LARGE_FILES */

/* restrict keyword */
#define restrict __restrict__
