trace (chr (x));
trace (concat (x, y));
trace (eval (x));
trace (getTimer ());
trace (int (x));
trace (length (x));
trace (Number (x));
trace (ord (x));
trace (random (x));
trace (targetPath (x));
trace (typeOf (x));
