//gcc -Wall -Werror `pkg-config --libs --cflags libming glib-2.0` compiler.c -o copiler

#include <glib.h>
#include <ming.h>
#include <string.h>

/* This is what is used to compile the Actionscript parts of the source to
 * includable C data that can later be executed.
 * Note that this is pretty much a hack until someone writes a proper
 * Actionscript compiler for Swfdec.
 * Also note that the creation of the include-scripts should probably not be 
 * autorun, as we don't want to depend on external bugs, only on internal ones.
 */
static gboolean
write_data (guint8 *data, gsize len)
{
  gsize i;

  /* debug */
  //g_file_set_contents ("foo", (char *) data, len, NULL);

  /* skip SWF crap */
  data += 25;

  /* sanity checks */
  /* 1) ensure file is long enough */
  if (len < 31)
    return FALSE;
  i = data[0] + (data[1] << 8);
  data += 2;
  /* 2) ensure we have a DoAction tag */
  if (((i >> 6) & 0x3ff) != 12)
    return FALSE;
  i = i & 0x3F;
  if (i == 0x3F) {
    i = data[0] + (data[1] << 8) + (data[2] << 16) + (data[3] << 24);
    data += 4;
    len -= 31;
  } else {
    len -= 27;
  }
  /* 3) check size of tag is correct */
  if (i >= len + 2)
    return FALSE;
  /* 4) check a ShowFrame comes next */
  if (data[i] != 0x40 || data[i + 1] != 0x00)
    return FALSE;
  /* trust the data */
  len = i;
  for (i = 0; i < len; i++) {
    switch (i % 16) {
      case 0:
	if (i == 0)
	  g_print ("  0x%02X", data[i]);
	else
	  g_print (",\n  0x%02X", data[i]);
	break;
      case 4:
      case 8:
      case 12:
	g_print (",  0x%02X", data[i]);
	break;
      default:
	g_print (", 0x%02X", data[i]);
	break;
    }
  }
  g_print ("\n");
  return TRUE;
}

static void
output_array (guint8 b, void *data)
{
  GByteArray *array = data;

  g_byte_array_append (array, &b, 1);
}
  
static char *
get_name (const char *filename)
{
  char *end;

  end = strrchr (filename, '/');
  if (end)
    filename = end + 1;
  end = strchr (filename, '.');
  if (end)
    return g_strndup (filename, end - filename);
  else
    return g_strdup (filename);
}

int
main (int argc, char **argv)
{
  SWFMovie movie;
  SWFAction action;
  GByteArray *array;
  char *contents;
  GError *error = NULL;
  guint i;

  if (argc < 2) {
    g_print ("usage: %s FILE ...\n\n", argv[0]);
    return 1;
  }

  Ming_init ();
  Ming_setSWFCompression (-1);

  g_print ("/* This file is autogenerated, do not edit! */\n\n");
  for (i = 1; i < argc; i++) {
    if (!g_file_get_contents (argv[1], &contents, NULL, &error)) {
      g_printerr ("%s\n", error->message);
      g_error_free (error);
      error = NULL;
      return 1;
    }
    movie = newSWFMovie ();
    action = newSWFAction (contents);
    SWFMovie_add (movie, (SWFBlock) action);
    g_free (contents);

    array = g_byte_array_new ();
    SWFMovie_output (movie, output_array, array);
    contents = get_name (argv[i]);
    g_print ("/* compiled from %s */\n", argv[i]);
    g_print ("const unsigned char %s[] = {\n", contents);
    g_free (contents);
    if (!write_data (array->data, array->len)) {
      g_printerr ("failed extracting compiled data for %s\n", argv[i]);
      return 1;
    }
    g_print ("};\n\n");
    g_byte_array_free (array, TRUE);
  }
  return 0;
}
